---
title: "statement_question"
output:
  word_document: default
  html_document: default
date: "2024-04-17"
---

```{r}
#1. Write a script that will print “Even Number” if the variable x is an even number, otherwise print “Not Even”:
x <- 10

if (x %% 2 == 0) {
  print("Even Number")
} else {
  print("Not Even")
}

```

```{r}
#2. Write a script that will print ‘Is a Matrix’ if the variable x is a matrix, otherwise print “Not a Matrix”:
x <- matrix(1:4, nrow = 3)
x
if (is.matrix(x)) {
  print("Is a Matrix")
} else {
  print("Not a Matrix")
}

```

```{r}
#3.Create a script that given a numeric vector  x=c(3,7,1), will print out the elements in order from low to high i.e (1,3,7). 
# You must use if,else if, and else statements for your logic:
x <- c(3, 7, 1)

if (x[1] > x[2] && x[1] > x[3]) {
  if (x[2] > x[3]) {
    cat(x[3], x[2], x[1], sep = ", ")
  } else {
    cat(x[2], x[3], x[1], sep = ", ")
  }
} else if (x[2] > x[1] && x[2] > x[3]) {
  if (x[1] > x[3]) {
    cat(x[3], x[1], x[2], sep = ", ")
  } else {
    cat(x[1], x[3], x[2], sep = ", ")
  }
} else {
  if (x[1] > x[2]) {
    cat(x[2], x[1], x[3], sep = ", ")
  } else {
    cat(x[1], x[2], x[3], sep = ", ")
  }
}


```

```{r}
# 4. Write a script that uses if, else if, and else statements to print the max element in a numeric vector with 3 elements.
# Ex. x = c(3,7,1) 7 should be the output:
x <- c(15, 17, 18)

if (x[1] > x[2] && x[1] > x[3]) {
  print(x[1])
} else if (x[2] > x[1] && x[2] > x[3]) {
  print(x[2])
} else {
  print(x[3])
}

```
