---
title: "Dataframe_questions"
output:
  word_document: default
  html_document: default
date: "2024-04-17"
---
```{r}
# 1.Create a data frame named df_students with the following columns: ID, Name, Age, and Grade. Populate it with data for 5 students. Perform the following operations: Add a new column Passed that indicates with TRUE or FALSE whether each student passed (assume a passing grade is at least 60). Select and print only the rows of students who are 18 years or older.
df_students <- data.frame(
  ID = 1:5,
  Name = c("Alice", "Bob", "Charlie", "David", "Emma"),
  Age = c(20, 18, 19, 17, 21),
  Grade = c(75, 80, 55, 90, 40)
)

# Add a new column Passed
df_students$Passed <- df_students$Grade >= 60

# Select and print only the rows of students who are 18 years or older
older_students <- df_students[df_students$Age >= 18, ]
print(older_students)
```

```{r}
# 2.Suppose you have two data frames, df_A and df_B... Merge these data frames
df_A <- data.frame(
  ID = 1:3,
  Name = c("Alice", "Bob", "Charlie"),
  Age = c(20, 18, 19)
  
)
df_B <- data.frame(
  ID = 4:6,
  Grade = c(75, 80, 55)
)
#merged_df <- merge(df_A, df_B, by = "ID")
merged_df <- merge(df_A, df_B,by = "ID", all = TRUE)
merged_df
```

```{r}
#3. Given a data frame df_sales with columns Date, ProductID, Quantity, and Price...Calculate the total sales (Quantity * Price) for each product
# Create df_sales data frame
df_sales <- data.frame(
  Date = c("2024-04-01", "2024-04-01", "2024-04-02", "2024-04-02"),
  ProductID = c(1, 2, 1, 2),
  Quantity = c(10, 5, 8, 6),
  Price = c(2.5, 3.0, 4.0, 3.5)
)
df_sales$total_sales <- df_sales$Quantity * df_sales$Price
df_sales
```

```{r} 
#4. For iris data set...Calculate the average Sepal Length for each Species
data(iris)
head(iris)
# avg sepal length::
avg_sepal_length <- aggregate(Sepal.Length ~ Species, data = iris, FUN = mean)
avg_sepal_length
# new column Sepal.Area:::
iris$Sepal.Area <- iris$Sepal.Length * iris$Sepal.Width
iris$Sepal.Area
head(iris)
```

```{r} 
# For airquality data set...Calculate the average Ozone level for each month, excluding missing values..Determine the month with the highest average Ozone level
data(airquality)
head(airquality)
avg_ozone_month <- aggregate(Ozone ~ Month, data = airquality, FUN = function(x) mean(x, na.rm = TRUE))
avg_ozone_month
max_avg_ozone_month <- avg_ozone_month[which.max(avg_ozone_month$Ozone), "Month"]
max_avg_ozone_month
```



